#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "15i \\\tadd_header X-Served-By 63873-web-01;" /etc/nginx/nginx.conf
sudo service nginx restart
